name: Deploy to Surge

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: |
          surge --token ${{ secrets.SURGE_TOKEN }} ./src nik3ss-store3s.surge.sh ${{ secrets.SURGE_DOMAIN }}
